import Foundation

enum LearningContent {
    static let cards: [FocusArea: [LessonCard]] = [
        .anxiety: anxiety,
        .depression: depression,
        .addiction: addiction,
        .relationships: relationships,
        .growth: growth,
        .health: health,
    ]

    private static let anxiety = [
        lesson("anx-01", "Understand the alarm", "Alarm is not always danger", "Anxiety can activate a real protective response even when no immediate threat is present. The sensations are real; the prediction attached to them may still need checking.", "Name the sensation, then name the observable situation separately.", "NIMH · Anxiety disorders", "https://www.nimh.nih.gov/health/topics/anxiety-disorders"),
        lesson("anx-02", "Understand the alarm", "Panic has a body pattern", "Panic attacks can involve racing heart, dizziness, trembling, chest discomfort, breathlessness, and fear of losing control. New or unusual physical symptoms still deserve appropriate medical assessment.", "Write the sensations you notice without adding what you fear they mean.", "NIMH · Panic disorder", "https://www.nimh.nih.gov/health/publications/panic-disorder-when-fear-overwhelms"),
        lesson("anx-03", "Understand the alarm", "Anxiety is broader than worry", "Anxiety disorders include several patterns, such as generalized anxiety, panic, social anxiety, and phobias. A qualified clinician looks at duration, impairment, context, and other possible causes.", "Notice which situations, body sensations, or uncertainties most reliably start your pattern.", "NIMH · Anxiety disorders", "https://www.nimh.nih.gov/health/topics/anxiety-disorders"),
        lesson("anx-04", "Understand the alarm", "A symptom is not a diagnosis", "Sleep loss, substances, medications, thyroid problems, heart or breathing conditions, and other factors can overlap with anxiety symptoms. Self-help works best alongside assessment when symptoms are persistent or changing.", "List anything medical, sleep-related, or substance-related worth discussing with a clinician.", "NIMH · Anxiety disorders", "https://www.nimh.nih.gov/health/topics/anxiety-disorders"),
        lesson("anx-05", "Change the learning", "Avoidance teaches fear to stay", "Avoidance can bring fast relief, which may reinforce the belief that escape prevented catastrophe. Supported, gradual approach practice can create different learning.", "Choose the smallest safe version of one avoided situation and repeat it before increasing difficulty.", "NIMH · Psychotherapies", "https://www.nimh.nih.gov/health/topics/psychotherapies"),
        lesson("anx-06", "Change the learning", "Exposure is planned, not reckless", "Evidence-based exposure is collaborative and gradual. It is not forcing someone into danger, ignoring consent, or flooding the nervous system to prove toughness.", "Create a five-step ladder from mildly uncomfortable to difficult, and start near the bottom.", "NIMH · Psychotherapies", "https://www.nimh.nih.gov/health/topics/psychotherapies"),
        lesson("anx-07", "Change the learning", "Safety behaviors can hide progress", "Repeatedly checking, seeking certainty, or carrying a special escape may make it hard to learn that a situation can be tolerated without those protections. Safety needs and compulsive reassurance are not the same thing.", "Reduce one unnecessary reassurance behavior slightly while keeping genuine safety intact.", "NHS · CBT overview", "https://www.nhs.uk/mental-health/talking-therapies-medicine-treatments/talking-therapies-and-counselling/cognitive-behavioural-therapy-cbt/overview/"),
        lesson("anx-08", "Change the learning", "Measure approach, not calm", "The goal of practice is not to guarantee zero anxiety. A more useful measure is whether you stayed, learned, and acted according to your values while discomfort changed on its own timeline.", "After a practice, record what you approached and what you learned rather than only your anxiety score.", "NIMH · Psychotherapies", "https://www.nimh.nih.gov/health/topics/psychotherapies"),
        lesson("anx-09", "Work with thoughts", "CBT asks for accuracy", "Cognitive behavioral therapy does not require cheerful thoughts. It examines whether a conclusion is complete, supported, and useful enough to guide action.", "Write the prediction, evidence for it, evidence against it, and the most balanced conclusion.", "NHS · CBT overview", "https://www.nhs.uk/mental-health/talking-therapies-medicine-treatments/talking-therapies-and-counselling/cognitive-behavioural-therapy-cbt/overview/"),
        lesson("anx-10", "Work with thoughts", "Uncertainty cannot be eliminated", "Anxiety often demands a guarantee before action. Repeated checking can temporarily soothe that demand while teaching the mind that uncertainty itself is unsafe.", "Choose one low-risk decision and allow it to remain good enough without another check.", "NIMH · Anxiety disorders", "https://www.nimh.nih.gov/health/topics/anxiety-disorders"),
        lesson("anx-11", "Work with the body", "Bigger breaths are not always better", "Rapid or oversized breathing can intensify tingling, dizziness, and air hunger. A slower, comfortable, normal-size breath may be more useful than repeatedly trying to fill the lungs.", "Breathe gently in for four and out for six; stop and return to natural breathing if symptoms worsen.", "VA · Breathing guidance", "https://www.ptsd.va.gov/PTSD/disaster_events/for_providers/spr/docs/SPR02_Breathing.pdf"),
        lesson("anx-12", "Work with the body", "Grounding restores context", "Grounding directs attention toward present sensory information when the mind is absorbed in a feared future. It is a way to orient, not a test you can fail.", "Name three shapes, two sounds, and one point of physical support.", "VA · Mindful awareness", "https://www.va.gov/WHOLEHEALTHLIBRARY/tools/diaphragmatic-breathing.asp"),
        lesson("anx-13", "Work with the body", "Relaxation is optional", "Relaxation techniques are generally safe, but some people report increased anxiety, intrusive thoughts, or loss-of-control fears. Choice, open eyes, movement, and shorter practice can matter.", "If stillness feels worse, try a slow walk while naming what you see.", "NCCIH · Relaxation safety", "https://www.nccih.nih.gov/health/relaxation-techniques-what-you-need-to-know"),
        lesson("anx-14", "Build the foundation", "Sleep can change the volume", "Sleep and emotional regulation influence each other. A consistent schedule and enough opportunity for sleep can support coping, though sleep habits alone do not treat every anxiety disorder.", "Protect a repeatable wake time for the next three days.", "NHLBI · Healthy sleep", "https://www.nhlbi.nih.gov/health/sleep-deprivation/healthy-sleep-habits"),
        lesson("anx-15", "Build the foundation", "Movement can support care", "Regular physical activity supports physical and mental health. It can complement treatment, but a workout should not become punishment or a demand to erase anxiety immediately.", "Choose ten comfortable minutes of movement you can repeat this week.", "CDC · Physical activity", "https://www.cdc.gov/physical-activity/php/about/index.html"),
        lesson("anx-16", "Treatment and support", "Effective treatment can be combined", "Psychotherapy, medication, or both may be used depending on the person, the anxiety pattern, preferences, other conditions, and access. Finding the right fit can take adjustment.", "Write three questions you want to ask a licensed clinician about options and side effects.", "NIMH · Anxiety disorders", "https://www.nimh.nih.gov/health/topics/anxiety-disorders"),
        lesson("anx-17", "Treatment and support", "Track patterns, not perfection", "A brief log of trigger, body response, thought, action, and outcome can reveal what keeps the cycle going. Tracking should clarify care, not become another compulsion.", "Log one episode in five lines, then close the note.", "NHS · CBT overview", "https://www.nhs.uk/mental-health/talking-therapies-medicine-treatments/talking-therapies-and-counselling/cognitive-behavioural-therapy-cbt/overview/"),
        lesson("anx-18", "Treatment and support", "Know when self-help is not enough", "Persistent impairment, fainting, severe chest pain, new neurologic symptoms, substance withdrawal, or thoughts of self-harm need professional or urgent support rather than another breathing exercise.", "Save the contact for your clinician, local urgent care, and crisis support before you need it.", "NIMH · Find help", "https://www.nimh.nih.gov/health/find-help"),
    ]

    private static let depression = [
        lesson("dep-01", "Understand the pattern", "Depression is more than sadness", "Depression can affect mood, interest, energy, concentration, sleep, appetite, movement, guilt, and hope. Diagnosis considers the pattern, duration, impairment, and other causes.", "Describe what changed in behavior and function, not only how bad you feel.", "NIMH · Depression", "https://www.nimh.nih.gov/health/topics/depression"),
        lesson("dep-02", "Understand the pattern", "The future can look falsely permanent", "Depression can make a current state feel global and endless. That feeling is important information, but it is not reliable proof about every future day.", "Replace always and never with a dated, specific description of today.", "NIMH · Depression", "https://www.nimh.nih.gov/health/topics/depression"),
        lesson("dep-03", "Behavioral activation", "Action can come before motivation", "Low mood can reduce activity, reward, mastery, and connection. Behavioral approaches schedule small meaningful actions instead of waiting for motivation to arrive first.", "Choose one five-minute action connected to care, mastery, or connection.", "NIMH · Psychotherapies", "https://www.nimh.nih.gov/health/topics/psychotherapies"),
        lesson("dep-04", "Behavioral activation", "Make the action observable", "Vague goals such as be productive are hard to begin and hard to learn from. A useful plan identifies what, where, and when.", "Rewrite one goal as: At this time, in this place, I will do this for five minutes.", "NIMH · Psychotherapies", "https://www.nimh.nih.gov/health/topics/psychotherapies"),
        lesson("dep-05", "Thinking skills", "A thought is a mental event", "Depressive conclusions can feel complete while leaving out context, exceptions, and available support. CBT tests a thought rather than treating every thought as a command.", "Write one painful thought and one more specific statement that includes what remains changeable.", "NHS · CBT overview", "https://www.nhs.uk/mental-health/talking-therapies-medicine-treatments/talking-therapies-and-counselling/cognitive-behavioural-therapy-cbt/overview/"),
        lesson("dep-06", "Daily foundation", "Regularity reduces extra friction", "A modest rhythm for waking, meals, medication as prescribed, movement, and contact can reduce the number of decisions a low-energy brain must make.", "Anchor tomorrow with one wake cue and one planned meal.", "NIMH · Caring for mental health", "https://www.nimh.nih.gov/health/topics/caring-for-your-mental-health"),
        lesson("dep-07", "Daily foundation", "Connection can be low pressure", "Support does not require a perfect explanation. A short check-in, shared task, or request for company can interrupt isolation.", "Send: I am having a low day. No fixing needed. Can you check in later?", "NIMH · Caring for mental health", "https://www.nimh.nih.gov/health/topics/caring-for-your-mental-health"),
        lesson("dep-08", "Daily foundation", "Movement is support, not a moral test", "Physical activity can support health and mood, but depression may make initiation difficult. Choose an amount gentle enough that tomorrow still feels possible, and never use movement as punishment.", "Walk or stretch for five minutes, then notice whether continuing would feel caring or compulsory.", "CDC · Physical activity", "https://www.cdc.gov/physical-activity/php/about/index.html"),
        lesson("dep-09", "Treatment", "Treatment is adjustable", "Depression treatment can include psychotherapy, medication, brain stimulation therapies, lifestyle support, or combinations. Response and side effects should be reviewed with a qualified clinician.", "Track changes you want to discuss rather than stopping prescribed treatment on your own.", "NIMH · Depression", "https://www.nimh.nih.gov/health/topics/depression"),
        lesson("dep-10", "Treatment", "Physical health belongs in the picture", "Some medical conditions, medications, sleep disorders, and substances can contribute to depressive symptoms. A full assessment is more useful than assuming every symptom has one cause.", "List recent health, medication, sleep, or substance changes for your next appointment.", "NIMH · Depression", "https://www.nimh.nih.gov/health/topics/depression"),
        lesson("dep-11", "Maintenance", "A relapse plan is made while steadier", "Early warning signs can include sleep changes, withdrawal, missed care, rumination, and loss of routine. A written response plan makes support easier to activate.", "Name three warning signs and the first person you will contact.", "NIMH · Depression", "https://www.nimh.nih.gov/health/topics/depression"),
        lesson("dep-12", "Safety", "Hopelessness needs a human response", "Thoughts of death, self-harm, or being unable to stay safe require immediate human support. The app cannot provide emergency care.", "In the U.S. or Canada, call or text 988; in immediate danger, call emergency services.", "NIMH · Find help", "https://www.nimh.nih.gov/health/find-help"),
    ]

    private static let addiction = [
        lesson("rec-01", "Understand recovery", "Addiction is treatable", "Substance use disorders are health conditions shaped by biology, learning, environment, access, and stress. Effective care is not a character test.", "Replace one shame statement with a description of the pattern and the support needed.", "NIDA · Science of addiction", "https://nida.nih.gov/publications/drugs-brains-behavior-science-addiction/preface"),
        lesson("rec-02", "Understand recovery", "Cues can trigger learned urgency", "Places, people, emotions, and routines can become linked with use. A craving can be intense without being an instruction.", "Name the cue, change location, delay action, and contact support.", "NIDA · Science of addiction", "https://nida.nih.gov/publications/drugs-brains-behavior-science-addiction/preface"),
        lesson("rec-03", "Understand recovery", "Treatment must fit the person", "No single treatment is appropriate for everyone. Substance, medical risk, mental health, housing, relationships, culture, and personal goals all affect the plan.", "Ask which level of care and evidence-based options match your current risks.", "NIDA · Treatment principles", "https://nida.nih.gov/publications/principles-drug-addiction-treatment-research-based-guide-third-edition/principles-effective-treatment"),
        lesson("rec-04", "Safety first", "Withdrawal can require medical care", "Withdrawal from alcohol, benzodiazepines, and some other substances can be dangerous. Do not assume that stopping suddenly is always safe.", "Contact a medical professional or treatment service before attempting a risky withdrawal alone.", "SAMHSA · Find treatment", "https://findtreatment.gov/"),
        lesson("rec-05", "Safety first", "Tolerance can fall", "After abstinence or reduced use, a previously tolerated opioid amount can cause overdose. Mixing substances can further increase risk.", "Avoid using alone, carry naloxone where relevant, and learn local overdose response.", "CDC · Overdose prevention", "https://www.cdc.gov/overdose-prevention/about/index.html"),
        lesson("rec-06", "Safety first", "Naloxone buys time", "Naloxone can reverse an opioid overdose temporarily. Emergency help is still needed because its effects can wear off before the opioid does.", "Learn where to obtain naloxone and show a trusted person how to use it.", "CDC · Lifesaving naloxone", "https://www.cdc.gov/stop-overdose/caring/naloxone.html"),
        lesson("rec-07", "Evidence-based care", "Medication can be treatment", "FDA-approved medications can be part of care for opioid, alcohol, and tobacco use disorders. Using medication for recovery is not replacing one moral failure with another.", "Ask a licensed prescriber which options, benefits, and risks apply to you.", "NIDA · Treatment", "https://nida.nih.gov/publications/drugs-brains-behavior-science-addiction/treatment-recovery"),
        lesson("rec-08", "Evidence-based care", "Skills and rewards can change behavior", "Behavioral treatments can help people recognize cues, build coping skills, strengthen recovery behaviors, and create meaningful alternatives.", "Choose one immediate, healthy reward for completing a protective action today.", "NIDA · Treatment", "https://nida.nih.gov/publications/drugs-brains-behavior-science-addiction/treatment-recovery"),
        lesson("rec-09", "Work with urges", "Delay creates options", "Urges change over time even when they do not disappear immediately. Creating distance reduces automatic access and gives support time to arrive.", "Set ten minutes, move away from access, and call or message someone safe.", "SAMHSA · Recovery support", "https://www.samhsa.gov/find-support"),
        lesson("rec-10", "Work with urges", "Environment is part of treatment", "Access, sleep loss, stress, money, isolation, and routines can raise risk. Recovery planning changes conditions instead of relying only on heroic refusal.", "Remove one cue and make one supportive action easier to reach.", "NIDA · Treatment principles", "https://nida.nih.gov/publications/principles-drug-addiction-treatment-research-based-guide-third-edition/principles-effective-treatment"),
        lesson("rec-11", "Long-term recovery", "A setback changes the plan", "A return to use can signal that treatment intensity, medication, environment, or support needs adjustment. Immediate safety comes before analysis.", "After safety is secured, record what happened in the hour before use without insults or excuses.", "SAMHSA · About recovery", "https://www.samhsa.gov/substance-use/recovery/about"),
        lesson("rec-12", "Long-term recovery", "Community is one tool, not the whole system", "Peer groups can provide belonging and practical experience. They do not replace medical care, and no single recovery community fits everyone.", "Try one vetted support option and evaluate whether it increases safety, dignity, and follow-through.", "SAMHSA · Find support", "https://www.samhsa.gov/find-support"),
        lesson("rec-13", "Long-term recovery", "Co-occurring symptoms matter", "Anxiety, depression, trauma, pain, and substance use can interact. Integrated care is often more useful than asking which problem is the only real one.", "Tell a provider about both substance use and mental health symptoms as honestly as you can.", "SAMHSA · Co-occurring disorders", "https://www.samhsa.gov/co-occurring-disorders"),
        lesson("rec-14", "Long-term recovery", "Recovery can include more than abstinence", "Recovery may involve health, purpose, stable housing, relationships, medication, harm reduction, and community. Goals should still address immediate safety clearly.", "Name one recovery gain that is not simply a number of days.", "SAMHSA · About recovery", "https://www.samhsa.gov/substance-use/recovery/about"),
    ]

    private static let relationships = [
        lesson("rel-01", "Clear communication", "Observation is not accusation", "Conflict escalates when an interpretation is presented as a fact. Specific observable behavior creates more room for a useful response.", "Describe what a camera could have recorded before naming your interpretation.", "NIMH · Psychotherapies", "https://www.nimh.nih.gov/health/topics/psychotherapies"),
        lesson("rel-02", "Clear communication", "Requests need a behavior", "Be better leaves the other person guessing. A clear request identifies a doable action, while leaving room for an honest yes or no.", "Ask for one specific action, time, or follow-up.", "APA · Relationships", "https://www.apa.org/topics/relationships"),
        lesson("rel-03", "Clear communication", "Listening is not surrender", "Reflecting what someone said can confirm understanding without agreeing with every conclusion. Accuracy lowers needless argument.", "Before answering, summarize the other person's point and ask if you understood it.", "APA · Relationships", "https://www.apa.org/topics/relationships"),
        lesson("rel-04", "Regulation", "Pause before repair", "High activation narrows attention and flexible thinking. A planned pause can protect the conversation when it includes a clear return time.", "Say: I care about this. I need twenty minutes, and I will return at this time.", "APA · Stress", "https://www.apa.org/topics/stress"),
        lesson("rel-05", "Boundaries", "A boundary describes your action", "A boundary states what you will do to protect safety, time, or dignity. It is different from a threat meant to control another person.", "Use: If shouting begins, I will pause and leave the conversation.", "Love is Respect · Boundaries", "https://www.loveisrespect.org/resources/what-are-my-boundaries/"),
        lesson("rel-06", "Boundaries", "Consent is ongoing", "Consent must be voluntary, informed, specific, and reversible. Relationship status or past consent does not create permanent permission.", "Practice accepting a no without debate, punishment, or pressure.", "RAINN · Consent", "https://rainn.org/articles/what-is-consent"),
        lesson("rel-07", "Repair", "A useful apology names impact", "A repair attempt becomes more credible when it names the behavior, acknowledges impact, avoids excuses, and includes a concrete change.", "Write an apology without the word but, followed by what you will do differently.", "APA · Relationships", "https://www.apa.org/topics/relationships"),
        lesson("rel-08", "Connection", "Social connection supports health", "Supportive relationships can protect health and well-being. Connection quality matters; being around people is not automatically the same as feeling safe or supported.", "Choose one person with whom a small honest contact is possible.", "CDC · Social connectedness", "https://www.cdc.gov/social-connectedness/about/index.html"),
        lesson("rel-09", "Patterns", "A pattern is not a destiny", "Past relationships and attachment experiences can shape expectations, but a label should not become an excuse or a permanent identity. New behavior can be practiced.", "Name the trigger, your usual move, and one alternative response.", "APA · Relationships", "https://www.apa.org/topics/relationships"),
        lesson("rel-10", "Safety", "Abuse is not a communication problem", "Intimidation, stalking, coercion, threats, and violence change the priority from better dialogue to personalized safety support.", "Use a safe device to contact a trusted person or specialist service; call emergency services for immediate danger.", "National Domestic Violence Hotline", "https://www.thehotline.org/"),
    ]

    private static let growth = [
        lesson("gro-01", "Direction", "Values are practiced directions", "A goal can be completed; a value describes how you want to keep acting. Values help when results are delayed or outside your control.", "Complete: Today I can practice being ___ by doing ___.", "NIMH · Psychotherapies", "https://www.nimh.nih.gov/health/topics/psychotherapies"),
        lesson("gro-02", "Direction", "Fewer priorities create depth", "Attention is limited. Treating every desire as urgent scatters effort and makes feedback hard to read.", "Choose one important action for today and move the rest to a later list.", "NIMH · Caring for mental health", "https://www.nimh.nih.gov/health/topics/caring-for-your-mental-health"),
        lesson("gro-03", "Habits", "Environment carries behavior", "Cues, friction, timing, and access shape repeated action. Good design lowers how often a difficult decision must be remade.", "Make the useful action visible and the distracting action one step harder.", "NIMH · Caring for mental health", "https://www.nimh.nih.gov/health/topics/caring-for-your-mental-health"),
        lesson("gro-04", "Habits", "A minimum protects continuity", "All-or-nothing rules turn a partial success into a total failure. A small minimum keeps the behavior available on difficult days.", "Define the two-minute version of one habit.", "NIMH · Psychotherapies", "https://www.nimh.nih.gov/health/topics/psychotherapies"),
        lesson("gro-05", "Habits", "Tracking should answer a question", "Measurement is useful when it clarifies whether a behavior happened or a pattern is changing. Tracking everything can become avoidance disguised as control.", "Track one behavior for seven days and decide what the data will help you choose.", "CDC · Health behavior", "https://www.cdc.gov/healthyyouth/evaluation/pdf/brief4.pdf"),
        lesson("gro-06", "Learning", "Feedback is not identity", "A result describes what happened under certain conditions. It does not describe the total worth or fixed potential of the person.", "Write what the result suggests changing next time without using a character insult.", "APA · Resilience", "https://www.apa.org/topics/resilience"),
        lesson("gro-07", "Learning", "Practice needs recovery", "Learning and performance are affected by sleep, stress, and recovery. More effort is not always more adaptation.", "Protect one period of rest before adding another demand.", "NHLBI · Sleep and health", "https://www.nhlbi.nih.gov/health/sleep-deprivation"),
        lesson("gro-08", "Learning", "Reflection must return to action", "Review can reveal patterns, but endless self-analysis can become another way to postpone an uncertain step.", "End today's reflection with one action under ten minutes.", "NIMH · Caring for mental health", "https://www.nimh.nih.gov/health/topics/caring-for-your-mental-health"),
        lesson("gro-09", "Support", "Accountability needs dignity", "Useful accountability makes the next action clearer and safer. Humiliation may produce compliance without durable learning.", "Ask someone to check one specific commitment at one specific time.", "APA · Behavior", "https://www.apa.org/topics/behavioral-health"),
        lesson("gro-10", "Support", "Change is allowed to be ordinary", "Sustainable growth often looks repetitive: sleep, meals, focused work, repair, and return. Drama is not evidence of depth.", "Keep one unglamorous promise today and record it once.", "NIMH · Caring for mental health", "https://www.nimh.nih.gov/health/topics/caring-for-your-mental-health"),
    ]

    private static let health = [
        lesson("hea-01", "Movement", "Some activity is better than none", "Health benefits can begin below an ideal target. The right starting point depends on current ability, disability, symptoms, and medical context.", "Choose ten repeatable minutes of walking, mobility, or strength.", "CDC · Physical activity", "https://www.cdc.gov/physical-activity/php/about/index.html"),
        lesson("hea-02", "Movement", "Strength belongs in the week", "Adult activity guidance includes muscle-strengthening activity in addition to aerobic movement. Exercises and loads should fit current capacity.", "Choose one comfortable push, pull, squat, or carry pattern to learn.", "HHS · Physical Activity Guidelines", "https://health.gov/our-work/nutrition-physical-activity/physical-activity-guidelines"),
        lesson("hea-03", "Sleep", "Sleep quantity and quality both matter", "Adults generally need at least seven hours, with individual needs and age affecting the range. Persistent unrefreshing sleep deserves attention even when time in bed looks adequate.", "Log bedtime, wake time, and refreshed feeling for one week.", "CDC · About sleep", "https://www.cdc.gov/sleep/about/index.html"),
        lesson("hea-04", "Nutrition", "Fiber is a family of compounds", "Different fibers affect digestion differently. Beans, whole grains, vegetables, fruit, nuts, and seeds add variety; rapid increases can cause discomfort.", "Add one tolerated fiber-rich food and increase gradually.", "NIDDK · Eating and digestion", "https://www.niddk.nih.gov/health-information/digestive-diseases"),
        lesson("hea-05", "Nutrition", "Protein needs vary", "Protein supports tissue, enzymes, and many body functions. Needs vary with body size, age, activity, pregnancy, and health; more is not automatically better.", "Include a suitable protein source at one meal without turning the meal into a test.", "Dietary Guidelines for Americans", "https://www.dietaryguidelines.gov/"),
        lesson("hea-06", "Nutrition", "Added sugar needs context", "Guidance to limit added sugar does not make fruit, plain dairy, legumes, or all carbohydrate foods equivalent to candy and sweetened drinks.", "Compare added sugar on two foods while also checking fiber, protein, and serving context.", "Dietary Guidelines for Americans", "https://www.dietaryguidelines.gov/"),
        lesson("hea-07", "Hydration", "Water needs are not one exact number", "Total water includes beverages and water in food. Climate, activity, pregnancy, illness, medication, and kidney or heart conditions can change needs.", "Use the app goal as a reminder, then adjust with qualified care when needed.", "National Academies · Water intake", "https://www.nationalacademies.org/read/10925/chapter/2"),
        lesson("hea-08", "Gut and brain", "The gut-brain axis is two-way", "Neural, immune, endocrine, metabolic, and microbial pathways connect digestive and brain function. The science is important but does not support promises that one food cures anxiety or depression.", "Build one meal around tolerated variety rather than a miracle ingredient.", "NCCIH · Probiotics", "https://www.nccih.nih.gov/health/probiotics-what-do-we-know"),
        lesson("hea-09", "Measurement", "BMI is a screening measure", "BMI uses height and weight; it does not directly measure body fat or diagnose health. It should be interpreted with other information.", "Treat the number as one data point, not a grade.", "CDC · BMI FAQ", "https://www.cdc.gov/bmi/faq/index.html"),
        lesson("hea-10", "Change", "Repeatability is a health feature", "Extreme plans may produce a short burst while being difficult to maintain. A plan that works during an ordinary week often teaches more.", "Rewrite one health rule so it still works at sixty percent energy.", "CDC · Healthy weight", "https://www.cdc.gov/healthy-weight-growth/losing-weight/index.html"),
        lesson("hea-11", "Body respect", "Food is not a moral score", "A single meal does not define health, character, or progress. Compensation through purging, fasting, or punishing exercise can be dangerous.", "Return to the next regular meal and seek specialized support if compensation urges recur.", "NIMH · Eating disorders", "https://www.nimh.nih.gov/health/topics/eating-disorders"),
        lesson("hea-12", "Care", "Symptoms deserve the right level of help", "Persistent pain, major bowel changes, fainting, rapid unexplained weight change, severe fatigue, or disordered eating need professional assessment rather than increasingly restrictive self-experiments.", "Write the symptom timeline and make an appropriate care appointment.", "NIH · Health information", "https://www.nih.gov/health-information"),
    ]

    private static func lesson(
        _ id: String,
        _ module: String,
        _ title: String,
        _ body: String,
        _ practice: String,
        _ sourceLabel: String,
        _ sourceURL: String
    ) -> LessonCard {
        LessonCard(
            id: id,
            module: module,
            title: title,
            body: body,
            practice: practice,
            sourceLabel: sourceLabel,
            sourceURL: URL(string: sourceURL)!
        )
    }
}
